aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 525077628079.dkr.ecr.ap-southeast-1.amazonaws.com

docker build -t devops-bootcamp/zzedj .

docker tag devops-bootcamp/zzedj:latest 525077628079.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp/zzedj:latest
